#ifndef BATTLESHIPS_MSGTYPES_H
#define BATTLESHIPS_MSGTYPES_H

enum MsgTypes
{
    DEMANDE_CREER = 000,

    CREER_PARTIE = 001,
    SUCCES_CREE = 002,

	TAILLE_TROP_PETITE = 003,
    TAILLE_TROP_GRANDE = 004,

    REJOINDRE_PARTIE = 010,
	PARTIE_REJOINTE = 011,
    
	CREER_PLATEAU = 020
	PLATEAU_CREE = 021,
	ERREUR_NB_BATEAU = 022,
	ERREUR_TAILLE_BATEAU = 023,
	ERREUR_DEPASSEMENT = 024,

	DEBUT = 030,
	ATTAQUER = 040,
    
	M_TOUCHE = 041,
	M_MANQUE = 042,
	M_COULE = 043,

	ERREUR_TIR_DEPASSE = 044,
	ERREUR_REPETITION_TIR = 045,

	GAGNE = 050,
	PERDU = 051,
	JOUE = 052,
};

enum StatutCase
{
    VIDE,
    OCCUPEE,
    MANQUE,
    TOUCHE,
    COULE
};

#endif